############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: Daumler_Website_Custom_Theme
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-reveal
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5

  #- path: github.com/daumler/Daumler_Website_Custom_Build_Hugo_Blox/modules/blox-plugin-netlify
  #- path: github.com/daumler/Daumler_Website_Custom_Build_Hugo_Blox/modules/blox-plugin-reveal
  #- path: github.com/daumler/Daumler_Website_Custom_Build_Hugo_Blox/modules/blox-bootstrap
